# Generated by Django 3.2.5 on 2021-08-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210825_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
