# Generated by Django 3.2.5 on 2021-09-06 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('owner', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_product/')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
